/* ═══════════════════════════════════════════════════════════════════
   VST Accessibility Intelligence — Static Data v1
   Client-side only. No serverless function required.
   ═══════════════════════════════════════════════════════════════════ */

window.VST_A11Y_DATA = {

  /* ── Accessible hotel scores ──────────────────────────────────── */
  hotels: [
    {
      id: 'h001',
      name: 'The Grand Continental',
      city: 'Paris', country: 'France',
      stars: 5,
      accessScore: 94,
      image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=600&q=80',
      features: {
        mobility: ['step-free-entry','roll-in-shower','lowered-bed','ceiling-hoist','wide-corridors','elevator','accessible-pool'],
        sensory: ['visual-fire-alarm','vibrating-pillow-alarm','braille-menus','tactile-floor-guides'],
        hearing: ['induction-loop','visual-doorbell','captioned-tv','bsl-staff'],
        vision: ['screen-reader-kiosk','large-print-menus','audio-descriptions'],
        medical: ['on-site-nurse','refrigerator-medication','dialysis-nearby','oxygen-rental'],
        dietary: ['allergen-menus','halal','vegan','gluten-free'],
      },
      certifications: ['NDA Gold', 'Visit France Accessible'],
      pricePerNight: 420,
      currency: 'GBP',
      accessibleRooms: 18,
      totalRooms: 210,
    },
    {
      id: 'h002',
      name: 'Barceló Raval',
      city: 'Barcelona', country: 'Spain',
      stars: 4,
      accessScore: 88,
      image: 'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=600&q=80',
      features: {
        mobility: ['step-free-entry','roll-in-shower','wide-corridors','elevator','accessible-pool','shower-chair'],
        sensory: ['visual-fire-alarm','vibrating-pillow-alarm','braille-menus'],
        hearing: ['induction-loop','visual-doorbell','captioned-tv'],
        vision: ['large-print-menus'],
        medical: ['refrigerator-medication','defibrillator'],
        dietary: ['allergen-menus','vegan','gluten-free'],
      },
      certifications: ['ONCE Accessible', 'Green Key'],
      pricePerNight: 185,
      currency: 'GBP',
      accessibleRooms: 12,
      totalRooms: 186,
    },
    {
      id: 'h003',
      name: 'Zoku Amsterdam',
      city: 'Amsterdam', country: 'Netherlands',
      stars: 4,
      accessScore: 91,
      image: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=600&q=80',
      features: {
        mobility: ['step-free-entry','roll-in-shower','wide-corridors','elevator','lowered-bed'],
        sensory: ['visual-fire-alarm','vibrating-pillow-alarm','braille-menus','quiet-room'],
        hearing: ['induction-loop','visual-doorbell','captioned-tv'],
        vision: ['large-print-menus','audio-descriptions','screen-reader-kiosk'],
        medical: ['refrigerator-medication','pharmacy-nearby'],
        dietary: ['allergen-menus','vegan','gluten-free','kosher'],
      },
      certifications: ['Toegankelijk Nederland A+'],
      pricePerNight: 210,
      currency: 'GBP',
      accessibleRooms: 9,
      totalRooms: 133,
    },
    {
      id: 'h004',
      name: 'The Ned London',
      city: 'London', country: 'United Kingdom',
      stars: 5,
      accessScore: 96,
      image: 'https://images.unsplash.com/photo-1455587734955-081b22074882?w=600&q=80',
      features: {
        mobility: ['step-free-entry','roll-in-shower','lowered-bed','ceiling-hoist','wide-corridors','elevator','accessible-pool','shower-chair'],
        sensory: ['visual-fire-alarm','vibrating-pillow-alarm','braille-menus','tactile-floor-guides','quiet-room'],
        hearing: ['induction-loop','visual-doorbell','captioned-tv','bsl-staff'],
        vision: ['screen-reader-kiosk','large-print-menus','audio-descriptions'],
        medical: ['on-site-nurse','refrigerator-medication','defibrillator','dialysis-nearby'],
        dietary: ['allergen-menus','halal','vegan','gluten-free','kosher'],
      },
      certifications: ['NDA Gold', 'VisitBritain Accessible'],
      pricePerNight: 580,
      currency: 'GBP',
      accessibleRooms: 24,
      totalRooms: 252,
    },
    {
      id: 'h005',
      name: 'Radisson Blu Scandinavia',
      city: 'Copenhagen', country: 'Denmark',
      stars: 4,
      accessScore: 93,
      image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80',
      features: {
        mobility: ['step-free-entry','roll-in-shower','wide-corridors','elevator','lowered-bed','shower-chair'],
        sensory: ['visual-fire-alarm','vibrating-pillow-alarm','braille-menus','quiet-room'],
        hearing: ['induction-loop','visual-doorbell','captioned-tv'],
        vision: ['large-print-menus','screen-reader-kiosk'],
        medical: ['refrigerator-medication','defibrillator','pharmacy-nearby'],
        dietary: ['allergen-menus','vegan','gluten-free'],
      },
      certifications: ['Disabled Persons Travel Card Partner'],
      pricePerNight: 245,
      currency: 'GBP',
      accessibleRooms: 14,
      totalRooms: 542,
    },
    {
      id: 'h006',
      name: 'Novotel Tokyo Shinjuku',
      city: 'Tokyo', country: 'Japan',
      stars: 4,
      accessScore: 87,
      image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=600&q=80',
      features: {
        mobility: ['step-free-entry','roll-in-shower','wide-corridors','elevator','shower-chair'],
        sensory: ['visual-fire-alarm','tactile-floor-guides','braille-menus'],
        hearing: ['visual-doorbell','captioned-tv'],
        vision: ['large-print-menus','tactile-floor-guides'],
        medical: ['refrigerator-medication','pharmacy-nearby'],
        dietary: ['allergen-menus','vegan','gluten-free'],
      },
      certifications: ['Accessible Japan Partner'],
      pricePerNight: 195,
      currency: 'GBP',
      accessibleRooms: 8,
      totalRooms: 284,
    },
  ],

  /* ── Accessible transport routes ─────────────────────────────── */
  transport: [
    {
      id: 't001',
      route: 'London → Paris',
      modes: ['eurostar'],
      accessScore: 95,
      features: ['step-free-boarding','wheelchair-spaces','accessible-toilet','assistance-service','priority-seating','induction-loop'],
      bookingNotes: 'Request wheelchair assistance 24h before departure via Eurostar Assisted Travel.',
      tags: ['mobility','hearing','vision'],
    },
    {
      id: 't002',
      route: 'Amsterdam → Brussels',
      modes: ['thalys','intercity'],
      accessScore: 92,
      features: ['step-free-boarding','wheelchair-spaces','accessible-toilet','induction-loop','large-print-timetables'],
      bookingNotes: 'NS Assistance service: call 030-751 5155 at least 1 hour before travel.',
      tags: ['mobility','hearing','vision'],
    },
    {
      id: 't003',
      route: 'New York → Washington DC',
      modes: ['amtrak'],
      accessScore: 88,
      features: ['step-free-boarding','wheelchair-spaces','accessible-toilet','priority-seating','hearing-loop'],
      bookingNotes: 'Amtrak accessibility desk: 1-800-USA-RAIL, option 2.',
      tags: ['mobility','hearing'],
    },
    {
      id: 't004',
      route: 'Tokyo → Osaka',
      modes: ['shinkansen'],
      accessScore: 97,
      features: ['step-free-boarding','wheelchair-spaces','accessible-toilet','tactile-platform-guides','audio-announcements','visual-display-boards'],
      bookingNotes: 'Green car carriage 7 has dedicated wheelchair bays. Book via JR East website.',
      tags: ['mobility','hearing','vision','sensory'],
    },
    {
      id: 't005',
      route: 'Barcelona → Madrid',
      modes: ['ave-high-speed'],
      accessScore: 91,
      features: ['step-free-boarding','wheelchair-spaces','accessible-toilet','assistance-service','induction-loop'],
      bookingNotes: 'Atendo service: book accessibility assistance 24h in advance on renfe.com.',
      tags: ['mobility','hearing'],
    },
    {
      id: 't006',
      route: 'Sydney → Melbourne',
      modes: ['xpt-train','coach'],
      accessScore: 83,
      features: ['wheelchair-spaces','accessible-toilet','priority-seating'],
      bookingNotes: 'NSW TrainLink accessibility team: 1300 235 160.',
      tags: ['mobility'],
    },
  ],

  /* ── Accessible venues by destination ───────────────────────── */
  venues: {
    'Paris': [
      { name: 'Musée d\'Orsay', type: 'museum', accessScore: 96, features: ['wheelchair-access','audio-guide','tactile-models','induction-loop','quiet-hours'], sensoryRating: 3, mobilityRating: 5 },
      { name: 'Eiffel Tower', type: 'landmark', accessScore: 78, features: ['wheelchair-access','elevator','audio-guide'], sensoryRating: 2, mobilityRating: 4 },
      { name: 'Centre Pompidou', type: 'museum', accessScore: 92, features: ['wheelchair-access','audio-guide','tactile-exhibits','large-print-guides','quiet-hours'], sensoryRating: 4, mobilityRating: 5 },
      { name: 'Jardins des Tuileries', type: 'outdoor', accessScore: 85, features: ['wheelchair-access','paved-paths','seating'], sensoryRating: 5, mobilityRating: 4 },
    ],
    'London': [
      { name: 'British Museum', type: 'museum', accessScore: 97, features: ['wheelchair-access','audio-guide','tactile-gallery','induction-loop','bsl-tours','quiet-hours','sensory-backpacks'], sensoryRating: 5, mobilityRating: 5 },
      { name: 'Tate Modern', type: 'museum', accessScore: 95, features: ['wheelchair-access','audio-guide','large-print','induction-loop','quiet-hours'], sensoryRating: 5, mobilityRating: 5 },
      { name: 'Hyde Park', type: 'outdoor', accessScore: 90, features: ['wheelchair-access','paved-paths','accessible-toilets','seating'], sensoryRating: 5, mobilityRating: 4 },
      { name: 'The Globe Theatre', type: 'theatre', accessScore: 88, features: ['wheelchair-access','induction-loop','audio-described-performances','captioned-performances','bsl-performances'], sensoryRating: 4, mobilityRating: 4 },
    ],
    'Barcelona': [
      { name: 'Sagrada Família', type: 'landmark', accessScore: 89, features: ['wheelchair-access','audio-guide','elevator','accessible-toilets'], sensoryRating: 2, mobilityRating: 4 },
      { name: 'Fundació Joan Miró', type: 'museum', accessScore: 93, features: ['wheelchair-access','audio-guide','tactile-materials','large-print','quiet-mornings'], sensoryRating: 4, mobilityRating: 5 },
      { name: 'Park Güell', type: 'outdoor', accessScore: 72, features: ['partial-wheelchair-access','audio-guide'], sensoryRating: 3, mobilityRating: 3 },
    ],
    'Tokyo': [
      { name: 'teamLab Borderless', type: 'museum', accessScore: 85, features: ['wheelchair-access','sensory-preview-map','quiet-hours'], sensoryRating: 2, mobilityRating: 4 },
      { name: 'Shinjuku Gyoen', type: 'outdoor', accessScore: 91, features: ['wheelchair-access','paved-paths','accessible-toilets','seating','quiet-zones'], sensoryRating: 5, mobilityRating: 4 },
      { name: 'Tokyo National Museum', type: 'museum', accessScore: 94, features: ['wheelchair-access','audio-guide','tactile-replicas','large-print','induction-loop'], sensoryRating: 4, mobilityRating: 5 },
    ],
    'Amsterdam': [
      { name: 'Rijksmuseum', type: 'museum', accessScore: 95, features: ['wheelchair-access','audio-guide','tactile-gallery','induction-loop','quiet-mornings','large-print'], sensoryRating: 5, mobilityRating: 5 },
      { name: 'Anne Frank House', type: 'museum', accessScore: 68, features: ['audio-guide','limited-wheelchair-access'], sensoryRating: 3, mobilityRating: 2 },
      { name: 'Vondelpark', type: 'outdoor', accessScore: 93, features: ['wheelchair-access','paved-paths','accessible-toilets','seating'], sensoryRating: 5, mobilityRating: 5 },
    ],
  },

  /* ── Sensory profiles ─────────────────────────────────────────── */
  sensoryProfiles: [
    {
      id: 'autism-low-support',
      label: 'Autism-friendly: Low support needs',
      description: 'Reduced visual noise, muted animations, predictable layouts. Filters for quiet venues and sensory-safe transport.',
      uiChanges: { reduceMotion: true, muteGold: false, simplifiedNav: true, highContrast: false, largeText: false },
      venueFilter: ['quiet-hours', 'quiet-zones', 'sensory-backpacks', 'quiet-mornings'],
    },
    {
      id: 'autism-high-support',
      label: 'Autism-friendly: High support needs',
      description: 'Minimal UI, single-focus layouts, no animations. Only fully sensory-safe venues and transport shown.',
      uiChanges: { reduceMotion: true, muteGold: true, simplifiedNav: true, highContrast: false, largeText: true },
      venueFilter: ['quiet-hours', 'quiet-zones', 'sensory-backpacks'],
    },
    {
      id: 'adhd',
      label: 'ADHD / Executive function support',
      description: 'Step-by-step planning mode. One decision at a time. Clear visual hierarchy. No clutter.',
      uiChanges: { reduceMotion: false, muteGold: false, simplifiedNav: true, highContrast: false, largeText: false },
      venueFilter: [],
    },
    {
      id: 'anxiety',
      label: 'Anxiety / Sensory sensitivity',
      description: 'Reduced stimulation, calm colour palette. Prioritises predictable, low-crowding venues and direct transport.',
      uiChanges: { reduceMotion: true, muteGold: true, simplifiedNav: false, highContrast: false, largeText: false },
      venueFilter: ['quiet-hours', 'quiet-zones', 'quiet-mornings'],
    },
    {
      id: 'dyslexia',
      label: 'Dyslexia-friendly',
      description: 'Increased line spacing, dyslexia-optimised font, shorter text blocks, icon-led navigation.',
      uiChanges: { reduceMotion: false, muteGold: false, simplifiedNav: false, highContrast: false, largeText: true, dyslexiaFont: true },
      venueFilter: [],
    },
  ],

  /* ── Medical accommodation search data ───────────────────────── */
  medicalNeeds: [
    { id: 'dialysis', label: 'Dialysis access', icon: '💧', description: 'Nearby dialysis centres, hotel partnerships with clinics.' },
    { id: 'oxygen', label: 'Oxygen supply', icon: '🫁', description: 'Oxygen rental services, airline approvals, hotel oxygen storage.' },
    { id: 'insulin', label: 'Insulin refrigeration', icon: '🧊', description: 'Guaranteed mini-fridge in room, pharmacy proximity.' },
    { id: 'mobility-aid', label: 'Mobility aid hire', icon: '♿', description: 'Wheelchair, scooter, and walking aid hire at destination.' },
    { id: 'peg-tube', label: 'PEG / enteral nutrition', icon: '🩺', description: 'Hotels with clinical kitchen facilities, enteral supply storage.' },
    { id: 'ventilator', label: 'Ventilator travel', icon: '🫀', description: 'Power socket guarantees, airline clearance support, hospital proximity.' },
    { id: 'allergy-severe', label: 'Severe allergy (anaphylaxis)', icon: '⚠️', description: 'Dedicated allergen-free rooms, epi-pen protocol hotels, hospital proximity.' },
    { id: 'mental-health', label: 'Mental health crisis support', icon: '🧠', description: 'Destinations with English-language mental health services, quiet environments.' },
  ],

  /* ── Mobility filter tags (display labels) ───────────────────── */
  mobilityTags: {
    'step-free-entry':      { label: 'Step-free entry',       icon: '🚶' },
    'roll-in-shower':       { label: 'Roll-in shower',        icon: '🚿' },
    'lowered-bed':          { label: 'Lowered bed',           icon: '🛏️' },
    'ceiling-hoist':        { label: 'Ceiling hoist',         icon: '⬆️' },
    'wide-corridors':       { label: 'Wide corridors',        icon: '↔️' },
    'elevator':             { label: 'Elevator access',       icon: '🛗' },
    'accessible-pool':      { label: 'Accessible pool',       icon: '🏊' },
    'shower-chair':         { label: 'Shower chair',          icon: '🪑' },
    'step-free-boarding':   { label: 'Step-free boarding',    icon: '🚆' },
    'wheelchair-spaces':    { label: 'Wheelchair spaces',     icon: '♿' },
    'accessible-toilet':    { label: 'Accessible toilet',     icon: '🚻' },
    'assistance-service':   { label: 'Assistance service',    icon: '🤝' },
    'priority-seating':     { label: 'Priority seating',      icon: '💺' },
    'paved-paths':          { label: 'Paved paths',           icon: '🛤️' },
    'wheelchair-access':    { label: 'Wheelchair access',     icon: '♿' },
    'partial-wheelchair-access': { label: 'Partial wheelchair', icon: '⚠️' },
  },

  /* ── Sensory / hearing / vision tags ─────────────────────────── */
  sensoryTags: {
    'visual-fire-alarm':       { label: 'Visual fire alarm',     icon: '🔆' },
    'vibrating-pillow-alarm':  { label: 'Vibrating alarm',       icon: '📳' },
    'braille-menus':           { label: 'Braille menus',         icon: '⠃' },
    'tactile-floor-guides':    { label: 'Tactile floor guides',  icon: '🦯' },
    'quiet-room':              { label: 'Quiet room available',  icon: '🤫' },
    'induction-loop':          { label: 'Induction loop',        icon: '🦻' },
    'visual-doorbell':         { label: 'Visual doorbell',       icon: '🔔' },
    'captioned-tv':            { label: 'Captioned TV',          icon: '📺' },
    'bsl-staff':               { label: 'BSL staff',             icon: '🤟' },
    'screen-reader-kiosk':     { label: 'Screen-reader kiosk',   icon: '💻' },
    'large-print-menus':       { label: 'Large-print menus',     icon: '🔍' },
    'audio-descriptions':      { label: 'Audio descriptions',    icon: '🔊' },
    'tactile-models':          { label: 'Tactile models',        icon: '🤲' },
    'audio-guide':             { label: 'Audio guide',           icon: '🎧' },
    'tactile-gallery':         { label: 'Tactile gallery',       icon: '🖐️' },
    'quiet-hours':             { label: 'Quiet hours',           icon: '🤫' },
    'quiet-zones':             { label: 'Quiet zones',           icon: '🧘' },
    'sensory-backpacks':       { label: 'Sensory kits',          icon: '🎒' },
    'quiet-mornings':          { label: 'Quiet mornings',        icon: '🌅' },
    'hearing-loop':            { label: 'Hearing loop',          icon: '🦻' },
    'large-print-timetables':  { label: 'Large-print info',      icon: '🔍' },
    'tactile-platform-guides': { label: 'Tactile guides',        icon: '🦯' },
    'audio-announcements':     { label: 'Audio announcements',   icon: '📢' },
    'visual-display-boards':   { label: 'Visual displays',       icon: '📋' },
    'bsl-tours':               { label: 'BSL tours',             icon: '🤟' },
    'audio-described-performances':  { label: 'Audio-described shows', icon: '🎭' },
    'captioned-performances':        { label: 'Captioned shows',       icon: '📝' },
    'bsl-performances':              { label: 'BSL performances',      icon: '🤟' },
    'large-print':             { label: 'Large-print materials',  icon: '🔍' },
    'tactile-exhibits':        { label: 'Tactile exhibits',       icon: '🤲' },
    'tactile-replicas':        { label: 'Tactile replicas',       icon: '🤲' },
    'tactile-materials':       { label: 'Tactile materials',      icon: '🤲' },
    'seating':                 { label: 'Ample seating',          icon: '💺' },
    'accessible-toilets':      { label: 'Accessible toilets',     icon: '🚻' },
    'pharmacy-nearby':         { label: 'Pharmacy nearby',        icon: '💊' },
    'limited-wheelchair-access': { label: 'Limited wheelchair',   icon: '⚠️' },
    'sensory-preview-map':     { label: 'Sensory preview map',    icon: '🗺️' },
  },

};
